server:
  port: 8000

spring:
  application:
    name: micro-service-zuul-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1001/eureka/

zuul:
  routes:
    eureka-client: /client/**
    eureka-consumer: /consumer/**


